# Generated by Django 5.0 on 2024-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_driver_id_card_alter_driver_license_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/customer/face'),
        ),
    ]
