# Generated by Django 5.0 on 2024-04-27 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_customer_profile_picture_alter_driver_id_card_and_more'),
        ('vehicles', '0011_alter_truck_status_alter_truck_truck_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_available', models.BooleanField(blank=True, default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_customer', to='accounts.customer')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_driver', to='accounts.driver')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_driver', to='vehicles.truck')),
            ],
        ),
    ]
