# Generated by Django 5.0 on 2024-05-19 04:31

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='transfer_receipt',
            field=models.ImageField(blank=True, null=True, upload_to=booking.models.receipt_path),
        ),
    ]
