# Generated by Django 5.0 on 2024-05-19 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_profile_picture_alter_driver_id_card_and_more'),
        ('maintenance', '0004_columnaverages'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnaverages',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_driver', to='accounts.driver'),
        ),
    ]
