# Generated by Django 5.0 on 2024-05-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_gps',
            },
        ),
    ]
