# Generated by Django 5.0 on 2024-01-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
