# Generated by Django 5.0 on 2024-01-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_maintenance_status_alter_truck_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='model',
            new_name='truck_model',
        ),
    ]
