# Generated by Django 5.0 on 2024-01-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_model_truck_truck_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='status',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_maintained',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
