# Generated by Django 5.0 on 2024-03-13 07:23

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_maintenance_truck_alter_truck_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='back_view',
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.get_back_view_path),
        ),
        migrations.AddField(
            model_name='truck',
            name='front_view',
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.get_front_view_path),
        ),
        migrations.AddField(
            model_name='truck',
            name='side_view',
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.get_side_view_path),
        ),
        migrations.AddField(
            model_name='truck',
            name='top_view',
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.get_top_view_path),
        ),
    ]
