# Generated by Django 5.0 on 2024-03-14 01:09

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_truck_back_view_truck_front_view_truck_side_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='overall_view',
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.get_overall_view_path),
        ),
    ]
