# Generated by Django 5.0 on 2024-03-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_profile_picture_alter_driver_id_card_and_more'),
        ('vehicles', '0008_truck_truck_accepted_truck_truck_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='driver',
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ManyToManyField(null=True, related_name='truck_driver', to='accounts.driver'),
        ),
    ]
