# Generated by Django 5.0 on 2024-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_remove_truck_driver_truck_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER')], default='OK', max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_available',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
